import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Typothunder",
  description: "Generated by create next app",
  authors: [
    {
      name: "Bibek Jodd",
      url: "https://github.com/bibekjodd",
    },
    {
      name: "Bigyan Sapkota",
      url: "https://github.com/bigyan-sapkota",
    },
  ],
  keywords:
    "typeracer, online typing race, online typeracer, realtime typeracer, realtime race, typing race, multiplayer type racing, multiplayer typing",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
